[package]
name = "tcip-cli"
version.workspace = true
edition.workspace = true

[lints]
workspace = true

[dependencies]
tcip-runtime = { path = "../runtime" }
tcip-api = { path = "../api" }
tcip-tools = { path = "../tools" }
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
toml.workspace = true
uuid.workspace = true

[dev-dependencies]
tempfile.workspace = true
chrono.workspace = true
