/**
 * Dev-server proxy prefixes, generated by tools/generate_frontend_routes.py from the routes
 * the FastAPI app registers. Do not edit; vite.config.ts pairs each with the backend target.
 */

export interface DevProxyEntry {
  path: string;
  ws: boolean;
}

export const DEV_PROXY: DevProxyEntry[] = [
  { path: "/api", ws: true },
  { path: "/ws", ws: true },
];
