/**
 * Every backend path the browser calls, named for its method and its route.
 *
 * Generated by tools/generate_frontend_routes.py from the routes the FastAPI app registers.
 * Do not edit, and do not write a path string anywhere else in the frontend: this module is the
 * browser's only copy of the backend's paths. Regenerate after adding or renaming a route.
 */

export const ROUTES = {
  getAnnotateLabels: "/api/annotate/labels",
  getClassesImageStatus: "/api/classes/image_status",
  getClassesLoad: "/api/classes/load",
  getCoverage: "/api/coverage",
  getCoverageCompleteness: "/api/coverage/completeness",
  getCoverageGrid: "/api/coverage/grid",
  getDatasetTree: "/api/dataset/tree",
  getFsList: "/api/fs/list",
  getHealth: "/health",
  getImages: "/api/images",
  getImagesBands: "/api/images/bands",
  getImagesOverviewsStatus: "/api/images/overviews/status",
  getInferenceJobs: "/api/inference/jobs",
  getMetaReports: "/api/meta/reports",
  getMetaRetrospectives: "/api/meta/retrospectives",
  getProjects: "/api/projects",
  getResultsDeliveryEvents: "/api/results/delivery-events",
  getResultsModelsRegistered: "/api/results/models/registered",
  getResultsOperationalization: "/api/results/operationalization",
  getResultsOperationalizations: "/api/results/operationalizations",
  getResultsPlantMappingList: "/api/results/plant_mapping/list",
  getResultsTraitSpecStatement: "/api/results/trait-spec-statement",
  getResultsTraitSpecStatements: "/api/results/trait-spec-statements",
  getResultsTraits: "/api/results/traits",
  getReviewGenerationConf: "/api/review/generation_conf",
  getReviewImageStatuses: "/api/review/image_statuses",
  getReviewQueueByJobId: (jobId: string) => `/api/review/queue/${encodeURIComponent(jobId)}`,
  getRoot: "/",
  getSessionsLoad: "/api/sessions/load",
  getState: "/api/state",
  getTerminalStatus: "/api/terminal/status",
  getTrainingConfigs: "/api/training/configs",
  getTrainingConfigsByExperimentIdSplits: (experimentId: string) =>
    `/api/training/configs/${encodeURIComponent(experimentId)}/splits`,
  getTrainingMetricDirections: "/api/training/metric-directions",
  getTrainingRuns: "/api/training/runs",
  getTrainingRunsByRunId: (runId: string) => `/api/training/runs/${encodeURIComponent(runId)}`,
  getTuningRayDashboard: "/api/tuning/ray-dashboard",
  getTuningSweeps: "/api/tuning/sweeps",
  getTuningSweepsBySweepId: (sweepId: string) =>
    `/api/tuning/sweeps/${encodeURIComponent(sweepId)}`,
  getTuningSweepsBySweepIdTrials: (sweepId: string) =>
    `/api/tuning/sweeps/${encodeURIComponent(sweepId)}/trials`,
  getTuningSweepsBySweepIdTrialsByTrialIdMetrics: (sweepId: string, trialId: string) =>
    `/api/tuning/sweeps/${encodeURIComponent(sweepId)}/trials/${encodeURIComponent(trialId)}/metrics`,
  postAnnotateLabels: "/api/annotate/labels",
  postCanvasState: "/api/canvas/state",
  postClassesImageStatus: "/api/classes/image_status",
  postClassesImageStatusBulk: "/api/classes/image_status/bulk",
  postClassesImageStatusDerive: "/api/classes/image_status/derive",
  postClassesSave: "/api/classes/save",
  postCoverage: "/api/coverage",
  postCoverageCompleteness: "/api/coverage/completeness",
  postCoverageGridZoom: "/api/coverage/grid_zoom",
  postDatasetNav: "/api/dataset/nav",
  postDatasetSelect: "/api/dataset/select",
  postEventsByPanel: (panel: string) => `/api/events/${encodeURIComponent(panel)}`,
  postImagesOverviews: "/api/images/overviews",
  postInferenceJobsByJobIdCancel: (jobId: string) =>
    `/api/inference/jobs/${encodeURIComponent(jobId)}/cancel`,
  postInferenceLaunch: "/api/inference/launch",
  postProjectsActive: "/api/projects/active",
  postResultsExportCountCsv: "/api/results/export_count_csv",
  postResultsExportCsv: "/api/results/export_csv",
  postResultsOperationalizationConfirm: "/api/results/operationalization/confirm",
  postResultsPhenologyMeasurement: "/api/results/phenology_measurement",
  postResultsPlantMappingBuild: "/api/results/plant_mapping/build",
  postResultsPlantMappingLoad: "/api/results/plant_mapping/load",
  postResultsTraitSpecStatementConfirm: "/api/results/trait-spec-statement/confirm",
  postReviewAction: "/api/review/action",
  postReviewBackupLabels: "/api/review/backup_labels",
  postReviewMarkComplete: "/api/review/mark_complete",
  postReviewMatches: "/api/review/matches",
  postReviewQueueLaunch: "/api/review/queue/launch",
  postReviewValidateReference: "/api/review/validate_reference",
  postSessionsEnd: "/api/sessions/end",
  postSessionsImageEvent: "/api/sessions/image_event",
  postSessionsStart: "/api/sessions/start",
  postStateTab: "/api/state/tab",
  postTerminalSessions: "/api/terminal/sessions",
  postTerminalSessionsBySessionIdRestart: (sessionId: string) =>
    `/api/terminal/sessions/${encodeURIComponent(sessionId)}/restart`,
  postTrainingCompare: "/api/training/compare",
  postTrainingCompareBest: "/api/training/compare/best",
  postTrainingRuns: "/api/training/runs",
  postTrainingRunsByRunIdCancel: (runId: string) =>
    `/api/training/runs/${encodeURIComponent(runId)}/cancel`,
  postTrainingRunsByRunIdTensorboard: (runId: string) =>
    `/api/training/runs/${encodeURIComponent(runId)}/tensorboard`,
  postTuningSweeps: "/api/tuning/sweeps",
  postTuningSweepsBySweepIdCancel: (sweepId: string) =>
    `/api/tuning/sweeps/${encodeURIComponent(sweepId)}/cancel`,
  postTuningSweepsBySweepIdTensorboard: (sweepId: string) =>
    `/api/tuning/sweeps/${encodeURIComponent(sweepId)}/tensorboard`,
  postTuningSweepsBySweepIdTrialsByTrialIdTensorboard: (sweepId: string, trialId: string) =>
    `/api/tuning/sweeps/${encodeURIComponent(sweepId)}/trials/${encodeURIComponent(trialId)}/tensorboard`,
  postTuningSweepsBySweepIdTrialsByTrialIdTensorboardStop: (sweepId: string, trialId: string) =>
    `/api/tuning/sweeps/${encodeURIComponent(sweepId)}/trials/${encodeURIComponent(trialId)}/tensorboard/stop`,
  socketInferenceJobsByJobIdStream: (jobId: string) =>
    `/api/inference/jobs/${encodeURIComponent(jobId)}/stream`,
  socketTerminalWsBySessionId: (sessionId: string) =>
    `/api/terminal/ws/${encodeURIComponent(sessionId)}`,
  socketTrainingRunsByRunIdStream: (runId: string) =>
    `/api/training/runs/${encodeURIComponent(runId)}/stream`,
  socketWsPanelByPanel: (panel: string) => `/ws/panel/${encodeURIComponent(panel)}`,
  socketWsState: "/ws/state",
} as const;
