/**
 * Every backend path the browser calls, named for its method and its route.
 *
 * Generated by tools/generate_frontend_routes.py from the routes the FastAPI app registers.
 * Do not edit, and do not write a path string anywhere else in the frontend: this module is the
 * browser's only copy of the backend's paths. Regenerate after adding or renaming a route.
 */

export const ROUTES = {
  getAnnotateLabels: "/api/annotate/labels",
  getAnnotateProposals: "/api/annotate/proposals",
  getAnnotateQueueByJobId: (jobId: string) => `/api/annotate/queue/${encodeURIComponent(jobId)}`,
  getDatasetTree: "/api/dataset/tree",
  getFsList: "/api/fs/list",
  getHealth: "/health",
  getImages: "/api/images",
  getImagesBands: "/api/images/bands",
  getImagesOverviewsStatus: "/api/images/overviews/status",
  getImagesServingGrid: "/api/images/serving_grid",
  getInferenceJobs: "/api/inference/jobs",
  getMetaReports: "/api/meta/reports",
  getMetaRetrospectives: "/api/meta/retrospectives",
  getProjects: "/api/projects",
  getResultsDeliveryEvents: "/api/results/delivery-events",
  getResultsModelsRegistered: "/api/results/models/registered",
  getResultsPlantMappingList: "/api/results/plant_mapping/list",
  getResultsTraits: "/api/results/traits",
  getRoot: "/",
  getSessionsLoad: "/api/sessions/load",
  getState: "/api/state",
  getSubjectsLoad: "/api/subjects/load",
  getTerminalStatus: "/api/terminal/status",
  getTrainingMetricDirections: "/api/training/metric-directions",
  getTrainingRuns: "/api/training/runs",
  getTrainingRunsByExperimentId: (experimentId: string) =>
    `/api/training/runs/${encodeURIComponent(experimentId)}`,
  getTrainingRunsByExperimentIdSplits: (experimentId: string) =>
    `/api/training/runs/${encodeURIComponent(experimentId)}/splits`,
  postAnnotateLabels: "/api/annotate/labels",
  postAnnotateQueueLaunch: "/api/annotate/queue/launch",
  postCanvasState: "/api/canvas/state",
  postDatasetNav: "/api/dataset/nav",
  postDatasetSelect: "/api/dataset/select",
  postEventsByPanel: (panel: string) => `/api/events/${encodeURIComponent(panel)}`,
  postImagesOverviews: "/api/images/overviews",
  postInferenceJobsByJobIdCancel: (jobId: string) =>
    `/api/inference/jobs/${encodeURIComponent(jobId)}/cancel`,
  postInferenceLaunch: "/api/inference/launch",
  postProjectsOpen: "/api/projects/open",
  postProjectsRemove: "/api/projects/remove",
  postProjectsRename: "/api/projects/rename",
  postResultsExportCountCsv: "/api/results/export_count_csv",
  postResultsExportCsv: "/api/results/export_csv",
  postResultsPhenologyMeasurement: "/api/results/phenology_measurement",
  postResultsPlantMappingBuild: "/api/results/plant_mapping/build",
  postResultsPlantMappingLoad: "/api/results/plant_mapping/load",
  postResultsTraitsConfirm: "/api/results/traits/confirm",
  postSessionsEnd: "/api/sessions/end",
  postSessionsImageEvent: "/api/sessions/image_event",
  postStateTab: "/api/state/tab",
  postSubjectsSave: "/api/subjects/save",
  postTerminalSessions: "/api/terminal/sessions",
  postTerminalSessionsBySessionIdRestart: (sessionId: string) =>
    `/api/terminal/sessions/${encodeURIComponent(sessionId)}/restart`,
  postTerminalSessionsBySessionIdSubmit: (sessionId: string) =>
    `/api/terminal/sessions/${encodeURIComponent(sessionId)}/submit`,
  postTrainingCompare: "/api/training/compare",
  postTrainingCompareBest: "/api/training/compare/best",
  postTrainingRuns: "/api/training/runs",
  postTrainingRunsByExperimentIdCancel: (experimentId: string) =>
    `/api/training/runs/${encodeURIComponent(experimentId)}/cancel`,
  postTrainingRunsByExperimentIdTensorboard: (experimentId: string) =>
    `/api/training/runs/${encodeURIComponent(experimentId)}/tensorboard`,
  socketInferenceJobsByJobIdStream: (jobId: string) =>
    `/api/inference/jobs/${encodeURIComponent(jobId)}/stream`,
  socketTerminalWsBySessionId: (sessionId: string) =>
    `/api/terminal/ws/${encodeURIComponent(sessionId)}`,
  socketTrainingRunsByExperimentIdStream: (experimentId: string) =>
    `/api/training/runs/${encodeURIComponent(experimentId)}/stream`,
  socketWsPanelByPanel: (panel: string) => `/ws/panel/${encodeURIComponent(panel)}`,
  socketWsState: "/ws/state",
} as const;
