/**
 * Types generated by scripts/generate_frontend_types.py from the pydantic models that declare
 * them (routes/_coverage_models.py, routes/coverage.py, routes/review.py,
 * tcip_web.state.GuiVocabulary, tcip_mcp.web_client, tcip_web.jobstore). Do not edit by hand.
 */

export const RENDER_CACHE_VERSION = 2;

export const TAB_NAMES = ["annotate", "review", "training", "tuning", "inference", "results", "meta"] as const;

export const TERMINAL_STATUSES = ["cancelled", "completed", "failed", "interrupted"] as const;

export type JobStatus = "pending" | "running" | "completed" | "failed" | "cancelled" | "interrupted";

export interface GridGeometry {
  width: number;
  height: number;
  tile_size: number;
  overlap: number;
  cols: number;
  rows: number;
}

export interface StatsSource {
  read: "none" | "dtype_full_scale" | "served_array" | "window_sample" | "overview";
  seed?: number | null;
  pixel_fraction?: number | null;
  overview_scale?: number | null;
}

export interface WorkingScaleBar {
  value: number;
  source: string;
}

export interface CoverageViewing {
  bands?: string | null;
  stretch?: "minmax" | "percent_clip" | "none" | null;
  stats_source: StatsSource | null;
  display_bounds: [number | null, number | null][] | null;
  base_served_size: string | null;
  working_scale_bar: WorkingScaleBar | null;
}

export interface CoverageRecord {
  grid: GridGeometry;
  cells_served_at_native: string[];
  cells_swept: string[];
  viewing: CoverageViewing;
  updated_at: string;
}

export interface CoveragePayload {
  image_path: string;
  subject?: string | null;
  date: string | null;
  dataset_root?: string | null;
  grid: GridGeometry;
  cells_served_at_native?: string[];
  cells_swept?: string[];
  viewing: CoverageViewing;
}

export interface ActionPayload {
  dataset_root: string;
  image_name: string;
  image_path: string;
  gt_path?: string | null;
  pred_path?: string | null;
  det_type: string;
  class_name: string;
  conf?: number | null;
  iou?: number | null;
  gt_idx?: number | null;
  pred_idx?: number | null;
  bbox: [number, number, number, number];
  action: "accepted" | "rejected" | "edited" | "swept";
  user?: string | null;
  edited_box?: [number, number, number, number] | null;
  edited_points?: number[][] | null;
  iou_threshold?: number;
  conf_threshold?: number;
  filter_type?: string;
  filter_class?: string;
  subject?: string | null;
  attribute?: string | null;
}

export interface GuiVocabulary {
  active_tab: "annotate" | "review" | "training" | "tuning" | "inference" | "results" | "meta";
  mode: "box" | "polygon" | "point";
}
