/**
 * Types generated by tools/generate_frontend_types.py from the pydantic models that declare
 * them (routes/annotate.py, routes/sessions.py, routes/images.py, routes/training.py,
 * routes/terminal.py, routes/projects.py, routes/results.py, tcip_mcp.experiments,
 * tcip_mcp.tools.training_tools, tcip_mcp.traits, tcip_mcp.web_client.GuiState), plus a
 * handful of runtime constants and vocabularies (routes/images.py, tcip_mcp.web_client,
 * tcip_mcp.experiments, tcip_mcp.subject_registry, tcip_mcp.agent_identity,
 * tcip_mcp.pipelines.training.evaluation, tcip_store.values, tcip_annotation.json_io,
 * tcip_web.jobstore). Do not edit by hand.
 */

export const RENDER_CACHE_VERSION = 6;

export const IMAGE_ERROR_HEADER = "X-TCIP-Image-Error";

export const OVERVIEWS_REQUIRED = "overviews_required";

export const NOT_FINITE_SUFFIX = "_state";

export const VAL_METRIC_PREFIX = "val_";

export const EPOCH_KEY = "epoch";

export const STEP_KEY = "step";

export const TIMESTAMP_KEY = "timestamp";

export const PERSON_NAME_RULE = "^(?![ \\t\\n\\v\\f\\r\\u00a0\\u1680\\u2000-\\u200a\\u2028\\u2029\\u202f\\u205f\\u3000\\ufeff]*user:[ \\t\\n\\v\\f\\r\\u00a0\\u1680\\u2000-\\u200a\\u2028\\u2029\\u202f\\u205f\\u3000\\ufeff]*$)[ \\t\\n\\v\\f\\r\\u00a0\\u1680\\u2000-\\u200a\\u2028\\u2029\\u202f\\u205f\\u3000\\ufeff]*(?:user:)?[ \\t\\n\\v\\f\\r\\u00a0\\u1680\\u2000-\\u200a\\u2028\\u2029\\u202f\\u205f\\u3000\\ufeff]*([^ \\t\\n\\v\\f\\r\\u00a0\\u1680\\u2000-\\u200a\\u2028\\u2029\\u202f\\u205f\\u3000\\ufeff](?:[\\d\\D]*[^ \\t\\n\\v\\f\\r\\u00a0\\u1680\\u2000-\\u200a\\u2028\\u2029\\u202f\\u205f\\u3000\\ufeff])?)[ \\t\\n\\v\\f\\r\\u00a0\\u1680\\u2000-\\u200a\\u2028\\u2029\\u202f\\u205f\\u3000\\ufeff]*$";

export const PANEL_EVENT_LABELS_WRITTEN = "labels_written";
export const PANEL_EVENT_ANNOTATE_FOCUS = "annotate_focus";
export const PANEL_EVENT_CANVAS_STATE_REQUEST = "canvas_state_request";

export const TAB_NAMES = ["setup", "annotate", "training", "inference", "results", "meta"] as const;

export const PLATFORM_PANEL_EVENTS = ["labels_written", "annotate_focus", "canvas_state_request"] as const;

export const TERMINAL_STATES = ["canceled", "completed", "failed", "interrupted"] as const;

export const ATTR_TYPES = ["categorical", "ordinal"] as const;

export const AGENT_IDENTITY_FIELDS = ["agent_client_name", "agent_client_version", "agent_session", "terminal_session"] as const;

export const FINISHED_STATES = ["complete", "negative"] as const;

export type JobStatus = "pending" | "running" | "completed" | "failed" | "canceled";

export type StretchMode = "minmax" | "percent_clip" | "none";

export type SubjectState = "complete" | "negative" | "partial" | "unannotated";

export type VerdictAction = "accepted" | "rejected";

export interface LaunchPriorityQueuePayload {
  checkpoint_path: string;
  images_dir: string;
  subject?: string | null;
  method?: string;
  budget?: number;
}

export interface CanvasStatePayload {
  project_id: string;
  tab: "setup" | "annotate" | "training" | "inference" | "results" | "meta";
  image_path: string;
  image: string;
  img_width?: number;
  img_height?: number;
  viewport?: Record<string, unknown> | null;
  mode?: string | null;
  active_subject?: string | null;
  cut_armed?: boolean | null;
  dirty?: boolean | null;
  user: string;
  classes?: Record<string, unknown>[];
  counts?: Record<string, unknown> | null;
  shapes?: Record<string, unknown>[] | null;
}

export interface ImageEntry {
  contribution_id: string;
  image_name: string;
  seconds: number;
  annotations_added: number;
  activity: "new_annotation" | "review" | "negative_confirmation";
}

export interface ImageEventPayload {
  contribution_id: string;
  image_name: string;
  seconds: number;
  annotations_added: number;
  activity: "new_annotation" | "review" | "negative_confirmation";
  user: string;
  project_id: string;
  started: string | null;
}

export interface SessionRef {
  project_id: string;
  started: string;
}

export interface SessionPlace {
  started: string;
  ended: boolean;
}

export interface SessionWrite {
  status: "ok" | "noop";
  session: SessionPlace | null;
}

export interface SessionSummary {
  user: string;
  started: string;
  ended: string | null;
  entries: ImageEntry[];
  images_annotated: number;
  total_annotations: number;
  total_time_seconds: number;
  seconds_by_activity: Record<string, number>;
  avg_seconds_per_annotation: number | null;
}

export interface ServingCell {
  name: string;
  level: number;
  x0: number;
  y0: number;
  x1: number;
  y1: number;
  nx0: number;
  ny0: number;
  nx1: number;
  ny1: number;
}

export interface ViewReads {
  reads: ServingCell[];
}

export interface RunRow {
  experiment_id: string;
  state: string;
  created: string;
  relaunched_from: string | null;
  sweep: string | null;
  trial_params: Record<string, unknown> | null;
  builder: string;
  task: string;
  images_dir: string | null;
  current_epoch: number | null;
  best_metric: number | null;
  best_metric_name: string | null;
  output_dir: string;
  status_error: string | null;
  heartbeat: string;
  launch: Record<string, string | null> | null;
}

export interface SweepGroup {
  sweep_id: string;
  state: string;
  status_error: string | null;
  input: Record<string, unknown>;
  objective: Record<string, unknown>;
  cancel_requested: boolean;
  heartbeat: string;
  trials: RunRow[];
  outcome: Record<string, unknown>;
}

export interface TrainingDetail {
  run: RunRow | null;
  sweep: SweepGroup | null;
  tensorboard_url: string | null;
}

export interface TrainingListing {
  runs: RunRow[];
  sweeps: SweepGroup[];
}

export interface TrainingRowFrame {
  type: "metric" | "batch";
  experiment_id: string;
  row: Record<string, unknown>;
}

export interface TrainingStatusFrame {
  type: "status";
  experiment_id: string;
  status: RunRow | null;
  error: string | null;
}

export interface TerminalInputFrame {
  type: "input";
  data: string;
}

export interface TerminalResizeFrame {
  type: "resize";
  rows: number;
  cols: number;
}

export interface CreateSessionRequest {
  provider: string;
  rows?: number;
  cols?: number;
  user: string;
}

export interface LaunchedProgram {
  provider: string;
  argv: string[];
  version: string | null;
  confinement: string | null;
  delivery_unverified: string | null;
  prepared: string[];
}

export interface TerminalLaunch {
  session_id: string;
  existing: boolean;
  launched: LaunchedProgram;
  ritual: string;
}

export interface ProviderStatus {
  id: string;
  name: string;
  unavailable_reason: string | null;
}

export interface TerminalStatus {
  providers: ProviderStatus[];
}

export interface SubmitRequest {
  text: string;
}

export interface ProjectSummary {
  id: string | null;
  display_name: string | null;
  site: string | null;
  record_problem: string | null;
  path: string;
  created: number;
  modified: number;
  dates: string[];
  subjects: string[];
  subjects_by_date: Record<string, string[]>;
  buckets_by_date: Record<string, string[]>;
  image_count: number;
  label_problem: string | null;
}

export interface OpenRequest {
  id: string;
  user: string;
}

export interface RemovalRequest {
  id: string;
  confirm_name: string;
  user: string;
}

export interface RenameRequest {
  id: string;
  display_name: string;
  user: string;
}

export interface PhenologyPayload {
  mapping_name: string;
  dataset_root: string;
  buckets: string[];
  trait: string;
  plants: string[];
  require_all_dates_complete?: boolean;
  show_unvalidated?: boolean;
}

export interface RegisteredModel {
  name: string;
  checkpoint_path: string;
  tags: string[];
  experiment_id: string | null;
}

export interface RegisteredModels {
  models: RegisteredModel[];
}

export interface AcknowledgmentPayload {
  reason: string;
  result_sha256: string;
}

export interface ExportCsvPayload {
  mapping_name: string;
  dataset_root: string;
  buckets: string[];
  trait: string;
  plants: string[];
  require_all_dates_complete?: boolean;
  payload: "curves" | "milestones";
  filename?: string | null;
  user: string;
  acknowledgment?: AcknowledgmentPayload | null;
}

export interface PerImageCountDelivery {
  kind: "per_image_count";
  dataset_root: string;
  bucket: string;
  trait: string;
}

export interface OrthomosaicPlantCountsDelivery {
  kind: "orthomosaic_plant_counts";
  dataset_root: string;
  bucket: string;
  plant_registry: string;
  delivered_phenotype: string;
  plants: string[];
  crop?: string;
  pipeline_version?: string;
  canopy_subject?: string;
  position_error_m?: number | null;
}

export interface ExportCountCsvPayload {
  delivery: PerImageCountDelivery | OrthomosaicPlantCountsDelivery;
  filename: string;
  user: string;
  acknowledgment?: AcknowledgmentPayload | null;
}

export interface MatchTolerance {
  value: number;
  source: "grid_pitch" | "stated" | "stated_capped";
}

export interface PlantRegistryReference {
  name: string;
  digest: string;
}

export interface PlantMappingDisclosure {
  name: string;
  dataset_id: string;
  dataset_root: string;
  built_at: string;
  record_sha256: string;
  nn_tolerance_m: MatchTolerance;
  capture_digests: Record<string, Record<string, string>>;
  captures_unverified: string[];
  plant_csvs_unverified: string[];
  dates_delivered: string[];
  images_unattributed: number;
  images_unattributed_scope: "delivered_dates";
  plant_attribution: string;
}

export interface PlantRegistryDisclosure {
  plant_registry: PlantRegistryReference;
  raster_identity: Record<string, unknown>;
  nn_tolerance_m: MatchTolerance;
  detections_unattributed: number;
  detections_unattributed_scope: "delivered_raster";
  plant_attribution: string;
  plants_outside_raster: string[];
}

export interface CanopySegmentsDocument {
  capture: string;
  stem: string;
  sha256: string;
  subject: string;
  n_segments: number;
}

export interface SegmentTieDisclosure {
  segment_index: number;
  plot_name: string;
  clearance_m: number;
}

export interface CanopySegmentDisclosure {
  plant_registry: PlantRegistryReference;
  raster_identity: Record<string, unknown>;
  canopy_segments: CanopySegmentsDocument;
  segment_ties: SegmentTieDisclosure[];
  position_error_m: number;
  segments_without_plant: number;
  plants_outside_raster: string[];
  plants_without_segment: string[];
  plants_within_position_error: string[];
  plants_with_ambiguous_detections: string[];
  detections_unattributed: number;
  detections_unattributed_by_source: Record<string, number>;
  detections_unattributed_scope: "delivered_raster";
  plant_attribution: string;
}

export interface Producer {
  checkpoint_sha256: string;
  experiment_id: string | null;
}

export interface BucketFinding {
  dataset_root: string;
  bucket: string;
  date: string | null;
  assessment_id: string | null;
  validated: boolean;
  reason: string | null;
}

export interface Acknowledgment {
  acknowledgment_id: string;
  acknowledged_by: string;
  reason: string;
  result_sha256: string;
  recorded_at: string;
}

export interface DeliveryEventRecord {
  event_id: string;
  door: string;
  delivery_kind: string;
  trait: string;
  trait_revision: number;
  trait_revision_sha256: string;
  output_path: string;
  output_sha256: string;
  producer: Producer;
  buckets: BucketFinding[];
  scale_assessment_id: string | null;
  validated: boolean;
  acknowledgment: Acknowledgment | null;
  population: string[];
  require_all_dates_complete: boolean | null;
  plant_mapping: PlantMappingDisclosure | PlantRegistryDisclosure | CanopySegmentDisclosure | null;
  produced_at: string;
}

export interface Operationalization {
  statement: string;
  mechanism: string;
  measured_subject: string;
  delivered_phenotypes: string[];
  delivered_value_keys: string[];
}

export interface PositiveState {
  attribute: string;
  value: string;
}

export interface TraitEntry {
  name: string;
  delivers: string[];
  positive_state: PositiveState | null;
  milestone_fractions: number[];
  milestone_on: string;
  majority_milestone: string;
  phenology_prefix: string;
  majority_label: string;
  count_objective: string;
  localization: "" | "center_match" | "iou_match";
  localization_tolerance: string;
  localization_tolerance_frac: number;
  iou_jitter_px: number | null;
  iou_margin: number | null;
  count_bias_tolerance_frac: number | null;
  count_error_tolerance: number | null;
  classifier_agreement_floor: number | null;
  ordinal_agreement_floor: number | null;
  regression_criterion: string;
  regression_skill_floor: number | null;
  scale_tolerance_frac: number | null;
  holdout_match_quality_floor: number | null;
  notes: string;
  operationalizations: Record<string, Operationalization>;
}

export interface TraitRevision {
  number: number;
  entry: TraitEntry;
  entry_sha256: string;
  rationale: string;
  relayed_note: string;
  proposed_at: string;
  confirmed_by: string | null;
  confirmed_at: string | null;
  withdrawn_by: string | null;
  withdrawn_at: string | null;
}

export interface ConfirmRevisionPayload {
  trait: string;
  revision: number;
  entry_sha256: string;
  user: string;
  confirmed: boolean;
}

export interface Stated {
  tile?: boolean | null;
  tile_size?: number | null;
  overlap?: number | null;
  postprocess?: string | null;
  cross_tile_nms?: number | null;
  conf?: number | null;
}

export interface GuiState {
  active_tab: "setup" | "annotate" | "training" | "inference" | "results" | "meta";
  view: ViewState;
  mode: "box" | "polygon" | "point";
  active_subject: string | null;
  dataset: DatasetSelection;
}

export interface DatasetSelection {
  dataset_root: string | null;
  subject: string | null;
  date: string | null;
  image_list: string[];
  current_image_index: number;
  images_dir: string | null;
  bucket: string | null;
}

export interface ViewState {
  scale: number;
  offset_x: number;
  offset_y: number;
}

export const GUI_STATE_DEFAULTS: GuiState = {
  "active_tab": "annotate",
  "view": {
    "scale": 1.0,
    "offset_x": 0.0,
    "offset_y": 0.0
  },
  "mode": "box",
  "active_subject": null,
  "dataset": {
    "dataset_root": null,
    "subject": null,
    "date": null,
    "image_list": [],
    "current_image_index": 0,
    "images_dir": null,
    "bucket": null
  }
};
