/**
 * Types generated by tools/generate_frontend_types.py from the pydantic models that declare
 * them (routes/_coverage_models.py, routes/coverage.py, routes/review.py, routes/training.py,
 * routes/terminal.py, tcip_web.state.GuiVocabulary), plus a handful of runtime constants
 * (routes/images.py, tcip_mcp.web_client, tcip_web.jobstore). Do not edit by hand.
 */

export const RENDER_CACHE_VERSION = 2;

export const IMAGE_ERROR_HEADER = "X-TCIP-Image-Error";

export const OVERVIEWS_REQUIRED = "overviews_required";

export const TAB_NAMES = ["annotate", "review", "training", "tuning", "inference", "results", "meta"] as const;

export const PANEL_EVENT_LABELS_WRITTEN = "labels_written";
export const PANEL_EVENT_ANNOTATE_FOCUS = "annotate_focus";
export const PANEL_EVENT_REVIEW_FOCUS = "review_focus";
export const PANEL_EVENT_ACTIVE_PROJECT_CHANGED = "active_project_changed";
export const PANEL_EVENT_CANVAS_STATE_REQUEST = "canvas_state_request";

export const PLATFORM_PANEL_EVENTS = ["labels_written", "annotate_focus", "review_focus", "active_project_changed", "canvas_state_request"] as const;

export const TERMINAL_STATUSES = ["cancelled", "completed", "failed", "interrupted"] as const;

export type JobStatus = "pending" | "running" | "completed" | "failed" | "cancelled" | "interrupted";

export interface GridGeometry {
  width: number;
  height: number;
  tile_size: number;
  overlap: number;
  cols: number;
  rows: number;
}

export interface StatsSource {
  read: "none" | "dtype_full_scale" | "served_array" | "window_sample" | "overview";
  seed?: number | null;
  pixel_fraction?: number | null;
  overview_scale?: number | null;
}

export interface WorkingScale {
  zoom: number;
  source: string;
}

export interface CoverageViewing {
  bands?: string | null;
  stretch?: "minmax" | "percent_clip" | "none" | null;
  stats_source: StatsSource | null;
  display_bounds: [number | null, number | null][] | null;
  base_served_size: string | null;
}

export interface CoverageRecord {
  grid: GridGeometry;
  cells_served_at_native: string[];
  cells_seen_at_scale: Record<string, number>;
  viewing: CoverageViewing;
  updated_at: string;
}

export interface CoveragePayload {
  image_path: string;
  subject?: string | null;
  date: string | null;
  dataset_root?: string | null;
  grid: GridGeometry;
  cells_served_at_native?: string[];
  cells_seen_at_scale?: Record<string, number>;
  viewing: CoverageViewing;
  replace?: boolean;
}

export interface CompletenessSetPayload {
  image_path: string;
  subject: string;
  dataset_root?: string | null;
  grid: GridGeometry;
  cell: string;
  complete: boolean;
  view_scale: number | null;
  user?: string | null;
}

export interface GridZoomPayload {
  subject: string;
  zoom: number;
  dataset_root?: string | null;
  user?: string | null;
}

export interface ActionPayload {
  dataset_root: string;
  image_name: string;
  image_path: string;
  gt_path?: string | null;
  pred_path?: string | null;
  det_type: string;
  class_name: string;
  conf?: number | null;
  iou?: number | null;
  gt_idx?: number | null;
  pred_idx?: number | null;
  bbox: [number, number, number, number];
  action: "accepted" | "rejected" | "edited" | "swept";
  user?: string | null;
  edited_box?: [number, number, number, number] | null;
  edited_points?: number[][] | null;
  iou_threshold?: number;
  conf_threshold?: number;
  filter_type?: string;
  filter_class?: string;
  subject?: string | null;
  attribute?: string | null;
}

export interface GuiVocabulary {
  active_tab: "annotate" | "review" | "training" | "tuning" | "inference" | "results" | "meta";
  mode: "box" | "polygon" | "point" | "map";
}

export interface TrainingMetricFrame {
  type: "metric";
  run_id: string;
  row: Record<string, unknown>;
}

export interface TrainingStatusFrame {
  type: "status";
  run_id: string;
  status: Record<string, unknown> | null;
  error: string | null;
}

export interface TerminalInputFrame {
  type: "input";
  data: string;
}

export interface TerminalResizeFrame {
  type: "resize";
  rows: number;
  cols: number;
}
