"""TCIP's storage seam: a root's records and logs in one database, and files written by path."""

from tcip_store.errors import (
    BackendUnavailable,
    BadKey,
    DecodeError,
    NotFound,
    StoreBusy,
    StoreError,
    StoreNotBound,
    TransactionMisuse,
    VersionConflict,
)
from tcip_store.file_backend import delete_blob, put_blob, read_blob_versioned
from tcip_store.model import REQUIRED, Key, LogPage, Version, Versioned, canonical_path
from tcip_store.sqlite_backend import Txn
from tcip_store.store import (
    append,
    bind,
    clear_log,
    delete,
    exists,
    keys,
    read,
    read_log,
    read_versioned,
    release_root,
    replace,
    stores,
    transaction,
    unbind,
)
from tcip_store.values import (
    check_json_value,
    decode_value,
    encode_log_line,
    encode_record,
    finite_or_none,
    non_finite_state,
    stored_number,
    stored_numbers,
)

__all__ = [
    "REQUIRED",
    "BackendUnavailable",
    "BadKey",
    "DecodeError",
    "Key",
    "LogPage",
    "NotFound",
    "StoreBusy",
    "StoreError",
    "StoreNotBound",
    "TransactionMisuse",
    "Txn",
    "Version",
    "VersionConflict",
    "Versioned",
    "append",
    "bind",
    "canonical_path",
    "check_json_value",
    "clear_log",
    "decode_value",
    "delete",
    "delete_blob",
    "encode_log_line",
    "encode_record",
    "exists",
    "finite_or_none",
    "keys",
    "non_finite_state",
    "put_blob",
    "read",
    "read_blob_versioned",
    "read_log",
    "read_versioned",
    "release_root",
    "replace",
    "stored_number",
    "stored_numbers",
    "stores",
    "transaction",
    "unbind",
]
