"""TCIP's storage seam: one interface for the platform's mutable records, logs, and blobs.

Every operation is addressed by a ``Key``, never by a path, and every write acquires that
key's lock inside the call. A store declares its kind, its codec, its concurrency policy and
its durability once, in the module that owns it; the bound backend decides where the bytes
actually live. What a backend cannot guarantee it refuses or declares, never degrades to.
"""

from tcip_store.errors import (
    BackendUnavailable,
    BadKey,
    CapabilityUnavailable,
    DecodeError,
    ListingUnsupported,
    NotFound,
    PolicyViolation,
    SchemaVersionRefused,
    StoreBusy,
    StoreError,
    StoreNotBound,
    TransactionMisuse,
    UnknownStore,
    VersionConflict,
    WrongKind,
)
from tcip_store.model import (
    REQUIRED,
    Capabilities,
    Key,
    LogPage,
    Version,
    Versioned,
    canonical_path,
)
from tcip_store.registry import (
    LOG_JSON,
    RECORD_JSON,
    Codec,
    StoreDescriptor,
    frozen_stores,
    get_descriptor,
    register_store,
    registered_stores,
    text_codec,
)
from tcip_store.schema_version import check_schema_version
from tcip_store.store import (
    Store,
    Txn,
    append,
    bind,
    blob_path,
    capabilities,
    clear_log,
    delete,
    exists,
    keys,
    open_blob,
    put_blob,
    put_blob_from_path,
    read,
    read_blob_versioned,
    read_log,
    read_versioned,
    replace,
    transaction,
    unbind,
    write_blob,
)
from tcip_store.values import (
    check_json_value,
    finite_or_none,
    non_finite_state,
    stored_number,
    stored_numbers,
)

__all__ = [
    "LOG_JSON",
    "RECORD_JSON",
    "REQUIRED",
    "BackendUnavailable",
    "BadKey",
    "Capabilities",
    "CapabilityUnavailable",
    "Codec",
    "DecodeError",
    "Key",
    "ListingUnsupported",
    "LogPage",
    "NotFound",
    "PolicyViolation",
    "SchemaVersionRefused",
    "Store",
    "StoreBusy",
    "StoreDescriptor",
    "StoreError",
    "StoreNotBound",
    "TransactionMisuse",
    "Txn",
    "UnknownStore",
    "Version",
    "VersionConflict",
    "Versioned",
    "WrongKind",
    "append",
    "bind",
    "blob_path",
    "canonical_path",
    "capabilities",
    "check_json_value",
    "check_schema_version",
    "clear_log",
    "delete",
    "exists",
    "finite_or_none",
    "frozen_stores",
    "get_descriptor",
    "keys",
    "non_finite_state",
    "open_blob",
    "put_blob",
    "put_blob_from_path",
    "read",
    "read_blob_versioned",
    "read_log",
    "read_versioned",
    "register_store",
    "registered_stores",
    "replace",
    "stored_number",
    "stored_numbers",
    "text_codec",
    "transaction",
    "unbind",
    "write_blob",
]
