"""Generate the browser's route-path module from the backend's registered routes.

The FastAPI app is the one declaration of what paths and methods exist. This script walks the
routes the app has actually registered and emits ``frontend/src/api/routes.ts``, so the browser
references a path by name instead of writing the string a second time. A route renamed, moved or
switched to another method changes the exported name, which fails the frontend type check at
every call site that still asks for the old one.

Run it after adding or renaming a route; it rewrites the module in place.
``tests/test_frontend_route_paths.py`` fails when the checked-in module is not what the current
routes produce, so a stale module does not reach a browser.
"""

from __future__ import annotations

import re
from collections.abc import Iterator
from pathlib import Path

from fastapi.routing import APIRoute, APIWebSocketRoute

_REPO_ROOT = Path(__file__).resolve().parent.parent
GENERATED_PATH = _REPO_ROOT / "packages" / "tcip-web" / "frontend" / "src" / "api" / "routes.ts"

_PARAM_RE = re.compile(r"\{([^}:]+)")
PRINT_WIDTH = 100

HEADER = """/**
 * Every backend path the browser calls, named for its method and its route.
 *
 * Generated by scripts/generate_frontend_routes.py from the routes the FastAPI app registers.
 * Do not edit, and do not write a path string anywhere else in the frontend: this module is the
 * browser's only copy of the backend's paths. Regenerate after adding or renaming a route.
 */

export const ROUTES = {
"""

FOOTER = "} as const;\n"


def _camel(token: str, *, upper_first: bool) -> str:
    """Turn one path segment or parameter name into a TypeScript identifier fragment."""
    words = [w for w in re.split(r"[^0-9a-zA-Z]+", token) if w]
    if not words:
        return ""
    head = words[0]
    head = head.capitalize() if upper_first else head[0].lower() + head[1:]
    return head + "".join(w.capitalize() for w in words[1:])


def route_name(path: str, method: str) -> str:
    """The exported name for one (path, method): its method, then its segments, then its params."""
    prefix = "socket" if method == "WEBSOCKET" else method.lower()
    segments = [s for s in path.strip("/").split("/") if s]
    if segments and segments[0] == "api":
        segments = segments[1:]
    parts = []
    for segment in segments:
        if segment.startswith("{"):
            parts.append("By" + _camel(_PARAM_RE.match(segment).group(1), upper_first=True))
        else:
            parts.append(_camel(segment, upper_first=True))
    return prefix + ("".join(parts) or "Root")


def iter_api_routes(app) -> Iterator[APIRoute | APIWebSocketRoute]:
    """Every ``APIRoute``/``APIWebSocketRoute`` the app has actually registered.

    Routers are included through wrapper objects rather than flattened onto the app, so this
    descends into whatever a registered entry carries its own routes under. The one walk of the
    app's real route tree; anything that needs to enumerate the app's routes calls this rather
    than re-descending the router tree itself.
    """
    for route in app.routes:
        if isinstance(route, (APIRoute, APIWebSocketRoute)):
            yield route
        elif hasattr(route, "original_router"):
            yield from iter_api_routes(route.original_router)


def collect_routes(app) -> list[tuple[str, str, str]]:
    """Every (name, path, method) the app has registered, sorted by name."""
    found: list[tuple[str, str, str]] = []
    for route in iter_api_routes(app):
        if isinstance(route, APIRoute):
            for method in sorted(route.methods - {"HEAD", "OPTIONS"}):
                found.append((route_name(route.path, method), route.path, method))
        else:
            found.append((route_name(route.path, "WEBSOCKET"), route.path, "WEBSOCKET"))

    by_name: dict[str, tuple[str, str, str]] = {}
    for entry in found:
        clash = by_name.get(entry[0])
        if clash is not None:
            raise SystemExit(
                f"two routes generate the name {entry[0]!r}: "
                f"{clash[2]} {clash[1]} and {entry[2]} {entry[1]}"
            )
        by_name[entry[0]] = entry
    return sorted(by_name.values())


def _entry(name: str, path: str) -> str:
    """One ROUTES member: a plain string, or an arrow taking the path's parameters."""
    params = _PARAM_RE.findall(path)
    if not params:
        return f'  {name}: "{path}",\n'
    args = ", ".join(f"{_camel(p, upper_first=False)}: string" for p in params)
    body = re.sub(
        r"\{([^}:]+)(?::[^}]*)?\}",
        lambda m: "${encodeURIComponent(" + _camel(m.group(1), upper_first=False) + ")}",
        path,
    )
    single = f"  {name}: ({args}) => `{body}`,\n"
    if len(single) - 1 <= PRINT_WIDTH:
        return single
    return f"  {name}: ({args}) =>\n    `{body}`,\n"


def render(app) -> str:
    """The full text of the generated module."""
    return HEADER + "".join(_entry(name, path) for name, path, _ in collect_routes(app)) + FOOTER


def main() -> int:
    from tcip_web.app import app

    GENERATED_PATH.write_text(render(app), encoding="utf-8", newline="\n")
    print(f"wrote {GENERATED_PATH}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
