"""Generate the browser's types from the pydantic models that declare them.

``routes/_coverage_models.py``, ``routes/coverage.py`` and ``routes/review.py`` declare a record's
shape once, in Python; this script projects each declared model into
``frontend/src/api/types.generated.ts`` through its own JSON schema, so the browser's types are
held to the backend's rather than hand-transcribed and left to drift. The mapper covers only the
schema shapes these models use (string/number/integer/boolean, a nullable union, a nested model by
``$ref``, an array, a fixed-length tuple, and a string-enum union); annotation keywords such as
``title``, ``default`` and ``additionalProperties`` are ignored rather than mapped, and any other
shape refuses by name.

Run it after changing a declared model; it rewrites the module in place.
``tests/test_generated_frontend_types.py`` fails when the checked-in module is not what the
current models produce, so a stale module does not reach a browser.
"""

from __future__ import annotations

import json
from pathlib import Path

from pydantic import BaseModel
from pydantic.json_schema import models_json_schema

_REPO_ROOT = Path(__file__).resolve().parent.parent
GENERATED_PATH = (
    _REPO_ROOT / "packages" / "tcip-web" / "frontend" / "src" / "api" / "types.generated.ts"
)

HEADER = """/**
 * Types generated by scripts/generate_frontend_types.py from the pydantic models it renders
 * (routes/_coverage_models.py, routes/coverage.py, routes/review.py). Do not edit by hand.
 */

"""

_PRIMITIVE = {"string": "string", "number": "number", "integer": "number", "boolean": "boolean"}


def declared_models() -> list[type[BaseModel]]:
    """The models this script renders, in the order their interfaces are emitted."""
    from tcip_web.routes._coverage_models import (
        CoverageRecord,
        CoverageViewing,
        GridGeometry,
        StatsSource,
        WorkingScaleBar,
    )
    from tcip_web.routes.coverage import CoveragePayload
    from tcip_web.routes.review import VerdictActionField

    return [GridGeometry, StatsSource, WorkingScaleBar, CoverageViewing, CoverageRecord,
            CoveragePayload, VerdictActionField]


def render_cache_version() -> int:
    from tcip_web.routes.images import RENDER_CACHE_VERSION

    return RENDER_CACHE_VERSION


def _ts_type(schema: dict, where: str) -> str:
    """One schema fragment as a TypeScript type expression, or a refusal naming ``where``."""
    if "$ref" in schema:
        return schema["$ref"].rsplit("/", 1)[-1]
    if "anyOf" in schema:
        parts: list[str] = []
        for part in schema["anyOf"]:
            mapped = _ts_type(part, where)
            if mapped not in parts:
                parts.append(mapped)
        return " | ".join(parts)
    if "enum" in schema:
        return " | ".join(json.dumps(v) for v in schema["enum"])
    kind = schema.get("type")
    if kind == "null":
        return "null"
    if kind in _PRIMITIVE:
        return _PRIMITIVE[kind]
    if kind == "array":
        if "prefixItems" in schema:
            items = ", ".join(_ts_type(s, where) for s in schema["prefixItems"])
            return f"[{items}]"
        if "items" in schema:
            return f"{_ts_type(schema['items'], where)}[]"
    raise SystemExit(f"generate_frontend_types.py cannot map the schema for {where}: {schema}")


def _interface(name: str, schema: dict) -> str:
    """One ``export interface`` block for a model's own JSON schema."""
    required = set(schema.get("required", []))
    lines = [f"export interface {name} {{\n"]
    for prop, prop_schema in schema.get("properties", {}).items():
        optional = "" if prop in required else "?"
        lines.append(f"  {prop}{optional}: {_ts_type(prop_schema, f'{name}.{prop}')};\n")
    lines.append("}\n")
    return "".join(lines)


def render() -> str:
    """The full text of the generated module."""
    models = declared_models()
    _, combined = models_json_schema([(m, "validation") for m in models])
    defs = combined["$defs"]
    body = "\n".join(_interface(m.__name__, defs[m.__name__]) for m in models)
    constant = f"export const RENDER_CACHE_VERSION = {render_cache_version()};\n\n"
    return HEADER + constant + body


def main() -> int:
    GENERATED_PATH.write_text(render(), encoding="utf-8", newline="\n")
    print(f"wrote {GENERATED_PATH}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
