"""Generate the browser's backend-declared types from the pydantic models that declare them.

``routes/images.py`` declares a served image's stats source and the region-serving grid;
``routes/annotate.py`` the review queue's launch and ``routes/sessions.py`` the annotation timing
entries and the sessions they amount to;
``tcip_mcp.experiments`` declares a run's row, a sweep's group, the listing of both and the detail
of one; ``routes/training.py`` and ``routes/terminal.py`` declare their WebSocket frame vocabularies, and
``routes/terminal.py`` the provider status, the session launch request and answer and the
submitted request;
``routes/projects.py`` declares the project summary and the open, removal and rename request
shapes; ``routes/results.py`` declares
the phenology and count export request shapes, the revision confirmation and the registered
models;
``tcip_mcp.traits`` declares the trait record and its revisions; and
``tcip_mcp.web_client.GuiState`` declares the GUI state the backend broadcasts, rendered as the
shape it serializes to, with its default instance as ``GUI_STATE_DEFAULTS``. This script projects
them into ``frontend/src/api/types.generated.ts`` through each model's own JSON schema. The
mapper covers only the schema shapes these models use (string/number/integer/boolean, a nullable
union, a nested model by ``$ref``, an array, a fixed-length tuple, a string-enum union, a
single-member ``Literal`` discriminator rendered as its literal type, and a free-form object
(``additionalProperties`` true, no ``properties``) rendered as ``Record<string, unknown>``);
annotation keywords such as ``title`` and ``default`` are ignored rather than mapped, a typed
mapping (``dict[str, T]``, ``additionalProperties`` a schema rather than a bare ``true``) renders
``Record<string, T>``, and any other shape (including an object with its own fixed, non-``$ref``
property set) refuses by name.
Each of ``web_client``'s own named ``PANEL_EVENT_*`` constants, the strings
:func:`string_constants` names, and the vocabularies :func:`tuple_constants` names are projected
alongside the models as runtime constants, and those :func:`literal_aliases` names as bare union
types, none of them schema-derived.

Run it after changing a declared model; it rewrites the module in place.
"""

from __future__ import annotations

import json
from pathlib import Path

from pydantic import BaseModel
from pydantic.json_schema import models_json_schema

_REPO_ROOT = Path(__file__).resolve().parent.parent
GENERATED_PATH = (
    _REPO_ROOT / "packages" / "tcip-web" / "frontend" / "src" / "api" / "types.generated.ts"
)

HEADER = """/**
 * Types generated by tools/generate_frontend_types.py from the pydantic models that declare
 * them (routes/annotate.py, routes/sessions.py, routes/images.py, routes/training.py,
 * routes/terminal.py, routes/projects.py, routes/results.py, tcip_mcp.experiments,
 * tcip_mcp.tools.training_tools, tcip_mcp.traits, tcip_mcp.web_client.GuiState), plus a
 * handful of runtime constants and vocabularies (routes/images.py, tcip_mcp.web_client,
 * tcip_mcp.experiments, tcip_mcp.subject_registry, tcip_mcp.agent_identity,
 * tcip_mcp.pipelines.training.evaluation, tcip_store.values, tcip_annotation.json_io,
 * tcip_web.jobstore). Do not edit by hand.
 */

"""

_PRIMITIVE = {"string": "string", "number": "number", "integer": "number", "boolean": "boolean"}


def declared_models() -> list[type[BaseModel]]:
    """The models this script renders, in the order their interfaces are emitted."""
    from tcip_web.routes.images import ServingCell, ServingGrid
    from tcip_web.routes.projects import OpenRequest, ProjectSummary, RemovalRequest, RenameRequest
    from tcip_web.routes.results import (
        AcknowledgmentPayload, ConfirmRevisionPayload, ExportCountCsvPayload, ExportCsvPayload,
        OrthomosaicPlantCountsDelivery, PerImageCountDelivery, PhenologyPayload, RegisteredModel,
        RegisteredModels,
    )
    from tcip_mcp.pipelines.execution import Stated
    from tcip_mcp.traits import Operationalization, PositiveState, TraitEntry, TraitRevision
    from tcip_mcp.pipelines.delivery_events_schema import (
        Acknowledgment, BucketFinding, CanopySegmentDisclosure, CanopySegmentsDocument,
        DeliveryEventRecord, MatchTolerance, PlantMappingDisclosure, PlantRegistryDisclosure,
        PlantRegistryReference, Producer, SegmentTieDisclosure,
    )
    from tcip_web.routes.annotate import LaunchPriorityQueuePayload
    from tcip_web.routes.sessions import ImageEntry, ImageEventPayload, SessionSummary
    from tcip_web.routes.terminal import (
        CreateSessionRequest, LaunchedProgram, ProviderStatus, SubmitRequest, TerminalInputFrame,
        TerminalLaunch, TerminalResizeFrame, TerminalStatus,
    )
    from tcip_mcp.experiments import RunRow, SweepGroup, TrainingDetail, TrainingListing
    from tcip_web.routes.training import TrainingMetricFrame, TrainingStatusFrame

    return [LaunchPriorityQueuePayload, ImageEntry, ImageEventPayload, SessionSummary,
            ServingCell, ServingGrid, RunRow, SweepGroup, TrainingDetail, TrainingListing,
            TrainingMetricFrame, TrainingStatusFrame, TerminalInputFrame,
            TerminalResizeFrame, CreateSessionRequest, LaunchedProgram, TerminalLaunch,
            ProviderStatus, TerminalStatus, SubmitRequest, ProjectSummary, OpenRequest, RemovalRequest, RenameRequest,
            PhenologyPayload, RegisteredModel, RegisteredModels,
            AcknowledgmentPayload, ExportCsvPayload, PerImageCountDelivery,
            OrthomosaicPlantCountsDelivery, ExportCountCsvPayload, MatchTolerance,
            PlantRegistryReference, PlantMappingDisclosure, PlantRegistryDisclosure,
            CanopySegmentsDocument, SegmentTieDisclosure, CanopySegmentDisclosure, Producer, BucketFinding, Acknowledgment,
            DeliveryEventRecord, Operationalization, PositiveState, TraitEntry, TraitRevision,
            ConfirmRevisionPayload, Stated]


TRANSPORT_MODELS = ("GuiState", "DatasetSelection", "ViewState")
"""The broadcast GUI state and the models it nests, rendered as they serialize."""


def render_cache_version() -> int:
    from tcip_web.routes.images import RENDER_CACHE_VERSION

    return RENDER_CACHE_VERSION


def string_constants() -> dict[str, str]:
    """Each backend string the frontend matches at runtime, by its constant's name."""
    from tcip_store.values import NOT_FINITE_SUFFIX
    from tcip_mcp.experiments import EPOCH_KEY, TIMESTAMP_KEY
    from tcip_mcp.pipelines.training.evaluation import VAL_METRIC_PREFIX
    from tcip_web.routes.images import IMAGE_ERROR_HEADER, OVERVIEWS_REQUIRED

    return {"IMAGE_ERROR_HEADER": IMAGE_ERROR_HEADER, "OVERVIEWS_REQUIRED": OVERVIEWS_REQUIRED,
            "NOT_FINITE_SUFFIX": NOT_FINITE_SUFFIX, "VAL_METRIC_PREFIX": VAL_METRIC_PREFIX,
            "EPOCH_KEY": EPOCH_KEY, "TIMESTAMP_KEY": TIMESTAMP_KEY}


def tuple_constants() -> dict[str, tuple[str, ...]]:
    """Each backend vocabulary the frontend iterates at runtime, by its constant's name."""
    from tcip_annotation.json_io import FINISHED_STATES
    from tcip_mcp.agent_identity import RECORD_FIELDS
    from tcip_mcp.experiments import TERMINAL_STATES
    from tcip_mcp.subject_registry import ATTR_TYPES
    from tcip_mcp.web_client import PLATFORM_PANEL_EVENTS, TAB_NAMES

    return {"TAB_NAMES": TAB_NAMES, "PLATFORM_PANEL_EVENTS": PLATFORM_PANEL_EVENTS,
            "TERMINAL_STATES": tuple(sorted(TERMINAL_STATES)), "ATTR_TYPES": ATTR_TYPES,
            "AGENT_IDENTITY_FIELDS": RECORD_FIELDS,
            "FINISHED_STATES": tuple(sorted(FINISHED_STATES))}


def platform_panel_event_constants() -> list[tuple[str, str]]:
    """Each named panel-event constant ``tcip_mcp.web_client`` declares (``PANEL_EVENT_*``), in
    the module's own declaration order: a consumer matching an event by one of these names never
    depends on where it sits in ``PLATFORM_PANEL_EVENTS``'s tuple."""
    from tcip_mcp import web_client

    return [(name, value) for name, value in vars(web_client).items()
            if name.startswith("PANEL_EVENT_") and isinstance(value, str)]


def literal_aliases() -> dict[str, tuple[str, ...]]:
    """Each server vocabulary the frontend names as a type, by its TypeScript alias name."""
    from typing import get_args

    from tcip_annotation.json_io import SubjectState
    from tcip_annotation.verdicts import VerdictAction
    from tcip_mcp.pipelines.band_stats import StretchMode
    from tcip_web.jobstore import JOB_STATES

    return {"JobStatus": JOB_STATES, "StretchMode": get_args(StretchMode),
            "SubjectState": get_args(SubjectState), "VerdictAction": get_args(VerdictAction)}


def _ts_type(schema: dict, where: str) -> str:
    """One schema fragment as a TypeScript type expression, or a refusal naming ``where``."""
    if "$ref" in schema:
        return schema["$ref"].rsplit("/", 1)[-1]
    if "anyOf" in schema or "oneOf" in schema:
        parts: list[str] = []
        for part in schema.get("anyOf") or schema["oneOf"]:
            mapped = _ts_type(part, where)
            if mapped not in parts:
                parts.append(mapped)
        return " | ".join(parts)
    if "enum" in schema:
        return " | ".join(json.dumps(v) for v in schema["enum"])
    if "const" in schema:
        # A one-member Literal renders as ``const``, not ``enum``: its own literal type, the
        # single value TypeScript can narrow the discriminated union on.
        return json.dumps(schema["const"])
    kind = schema.get("type")
    if kind is None and not schema.keys() - {"default", "title", "description"}:
        return "unknown"  # a field carried uninterpreted (``Any``): the backend reads it
    if kind == "null":
        return "null"
    if kind in _PRIMITIVE:
        return _PRIMITIVE[kind]
    if kind == "object":
        # A free-form object (no fixed property set) is the only object shape reached here: a
        # model's own fields arrive as a ``$ref`` instead, so a fixed non-``$ref`` shape refuses.
        if not schema.get("properties") and schema.get("additionalProperties") is True:
            return "Record<string, unknown>"
        if not schema.get("properties") and isinstance(schema.get("additionalProperties"), dict):
            # dict[str, T] (a typed mapping, not free-form): Record<string, T>.
            return f"Record<string, {_ts_type(schema['additionalProperties'], where)}>"
    if kind == "array":
        if "prefixItems" in schema:
            items = ", ".join(_ts_type(s, where) for s in schema["prefixItems"])
            return f"[{items}]"
        if "items" in schema:
            item_schema = schema["items"]
            item_type = _ts_type(item_schema, where)
            # A top-level union (anyOf, or an enum of more than one member) renders bare, with no
            # brackets of its own; parenthesize it so an array of it reads as ``(A | B)[]``.
            if "anyOf" in item_schema or len(item_schema.get("enum", [])) > 1:
                item_type = f"({item_type})"
            return f"{item_type}[]"
    raise SystemExit(f"generate_frontend_types.py cannot map the schema for {where}: {schema}")


def _interface(name: str, schema: dict) -> str:
    """One ``export interface`` block for a model's own JSON schema."""
    required = set(schema.get("required", []))
    lines = [f"export interface {name} {{\n"]
    for prop, prop_schema in schema.get("properties", {}).items():
        optional = "" if prop in required else "?"
        lines.append(f"  {prop}{optional}: {_ts_type(prop_schema, f'{name}.{prop}')};\n")
    lines.append("}\n")
    return "".join(lines)


def render() -> str:
    """The full text of the generated module."""
    from tcip_mcp.web_client import GuiState

    models = declared_models()
    _, combined = models_json_schema(
        [(m, "validation") for m in models] + [(GuiState, "serialization")])
    defs = combined["$defs"]
    body = "\n".join(_interface(m.__name__, defs[m.__name__]) for m in models)
    body += "\n" + "\n".join(_interface(name, defs[name]) for name in TRANSPORT_MODELS)
    defaults = json.dumps(GuiState().model_dump(mode="json"), indent=2)
    body += f"\nexport const GUI_STATE_DEFAULTS: GuiState = {defaults};\n"
    constant = f"export const RENDER_CACHE_VERSION = {render_cache_version()};\n\n"
    strings = "".join(f"export const {name} = {json.dumps(value)};\n\n"
                      for name, value in string_constants().items())
    panel_event_names = "".join(
        f"export const {name} = {json.dumps(value)};\n"
        for name, value in platform_panel_event_constants()) + "\n"
    tuples = "".join(f"export const {name} = [{', '.join(json.dumps(m) for m in members)}] as const;\n\n"
                     for name, members in tuple_constants().items())
    aliases = "".join(f"export type {name} = {' | '.join(json.dumps(m) for m in members)};\n\n"
                      for name, members in literal_aliases().items())
    return HEADER + constant + strings + panel_event_names + tuples + aliases + body


def main() -> int:
    GENERATED_PATH.write_text(render(), encoding="utf-8", newline="\n")
    print(f"wrote {GENERATED_PATH}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
