"""Generate the browser's backend-declared types from the pydantic models that declare them.

``routes/_coverage_models.py`` and ``routes/coverage.py`` declare the view-coverage record's
shape once, in Python; ``routes/review.py`` declares the review verdict's action vocabulary;
``routes/training.py`` and ``routes/terminal.py`` declare their WebSocket frame vocabularies; and
``tcip_web.state.GuiVocabulary`` declares the GUI's tab/mode vocabulary. This script projects
them into ``frontend/src/api/types.generated.ts`` through each model's own JSON schema, so the
browser's types are held to the backend's rather than hand-transcribed and left to drift. The
mapper covers only the schema shapes these models use (string/number/integer/boolean, a nullable
union, a nested model by ``$ref``, an array, a fixed-length tuple, a string-enum union, a
single-member ``Literal`` discriminator rendered as its literal type, and a free-form object
(``additionalProperties`` true, no ``properties``) rendered as ``Record<string, unknown>``);
annotation keywords such as ``title`` and ``default`` are ignored rather than mapped, a typed
mapping (``dict[str, T]``, ``additionalProperties`` a schema rather than a bare ``true``) renders
``Record<string, T>``, and any other shape (including an object with its own fixed, non-``$ref``
property set) refuses by name.
``tcip_mcp.web_client.TAB_NAMES`` and ``PLATFORM_PANEL_EVENTS``, each of ``web_client``'s own
named ``PANEL_EVENT_*`` constants, ``routes/images.py``'s ``IMAGE_ERROR_HEADER`` and
``OVERVIEWS_REQUIRED``, and ``tcip_web.jobstore.TERMINAL_STATUSES`` are projected alongside the
models as runtime constants, and ``tcip_web.jobstore.JobStatus`` as a bare union type, none of
them schema-derived.

Run it after changing a declared model; it rewrites the module in place.
``tests/test_generated_frontend_types.py`` fails when the checked-in module is not what the
current models produce, so a stale module does not reach a browser.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import get_args

from pydantic import BaseModel
from pydantic.json_schema import models_json_schema

_REPO_ROOT = Path(__file__).resolve().parent.parent
GENERATED_PATH = (
    _REPO_ROOT / "packages" / "tcip-web" / "frontend" / "src" / "api" / "types.generated.ts"
)

HEADER = """/**
 * Types generated by tools/generate_frontend_types.py from the pydantic models that declare
 * them (routes/_coverage_models.py, routes/coverage.py, routes/review.py, routes/training.py,
 * routes/terminal.py, tcip_web.state.GuiVocabulary), plus a handful of runtime constants
 * (routes/images.py, tcip_mcp.web_client, tcip_web.jobstore). Do not edit by hand.
 */

"""

_PRIMITIVE = {"string": "string", "number": "number", "integer": "number", "boolean": "boolean"}


def declared_models() -> list[type[BaseModel]]:
    """The models this script renders, in the order their interfaces are emitted."""
    from tcip_web.routes._coverage_models import (
        CoverageRecord,
        CoverageViewing,
        GridGeometry,
        StatsSource,
        WorkingScale,
    )
    from tcip_web.routes.coverage import CompletenessSetPayload, CoveragePayload, GridZoomPayload
    from tcip_web.routes.review import ActionPayload
    from tcip_web.routes.terminal import TerminalInputFrame, TerminalResizeFrame
    from tcip_web.routes.training import TrainingMetricFrame, TrainingStatusFrame
    from tcip_web.state import GuiVocabulary

    return [GridGeometry, StatsSource, WorkingScale, CoverageViewing, CoverageRecord,
            CoveragePayload, CompletenessSetPayload, GridZoomPayload, ActionPayload,
            GuiVocabulary, TrainingMetricFrame, TrainingStatusFrame, TerminalInputFrame,
            TerminalResizeFrame]


def render_cache_version() -> int:
    from tcip_web.routes.images import RENDER_CACHE_VERSION

    return RENDER_CACHE_VERSION


def image_error_header() -> str:
    from tcip_web.routes.images import IMAGE_ERROR_HEADER

    return IMAGE_ERROR_HEADER


def overviews_required() -> str:
    from tcip_web.routes.images import OVERVIEWS_REQUIRED

    return OVERVIEWS_REQUIRED


def tab_names() -> tuple[str, ...]:
    from tcip_mcp.web_client import TAB_NAMES

    return TAB_NAMES


def platform_panel_events() -> tuple[str, ...]:
    from tcip_mcp.web_client import PLATFORM_PANEL_EVENTS

    return PLATFORM_PANEL_EVENTS


def platform_panel_event_constants() -> list[tuple[str, str]]:
    """Each named panel-event constant ``tcip_mcp.web_client`` declares (``PANEL_EVENT_*``), in
    the module's own declaration order: a consumer matching an event by one of these names never
    depends on where it sits in ``PLATFORM_PANEL_EVENTS``'s tuple."""
    from tcip_mcp import web_client

    return [(name, value) for name, value in vars(web_client).items()
            if name.startswith("PANEL_EVENT_") and isinstance(value, str)]


def terminal_statuses() -> tuple[str, ...]:
    from tcip_web.jobstore import TERMINAL_STATUSES

    return tuple(sorted(TERMINAL_STATUSES))


def job_status_members() -> tuple[str, ...]:
    from tcip_web.jobstore import JobStatus

    return get_args(JobStatus)


def _ts_type(schema: dict, where: str) -> str:
    """One schema fragment as a TypeScript type expression, or a refusal naming ``where``."""
    if "$ref" in schema:
        return schema["$ref"].rsplit("/", 1)[-1]
    if "anyOf" in schema:
        parts: list[str] = []
        for part in schema["anyOf"]:
            mapped = _ts_type(part, where)
            if mapped not in parts:
                parts.append(mapped)
        return " | ".join(parts)
    if "enum" in schema:
        return " | ".join(json.dumps(v) for v in schema["enum"])
    if "const" in schema:
        # A one-member Literal renders as ``const``, not ``enum``: its own literal type, the
        # single value TypeScript can narrow the discriminated union on.
        return json.dumps(schema["const"])
    kind = schema.get("type")
    if kind == "null":
        return "null"
    if kind in _PRIMITIVE:
        return _PRIMITIVE[kind]
    if kind == "object":
        # A free-form object (no fixed property set) is the only object shape reached here: a
        # model's own fields arrive as a ``$ref`` instead, so a fixed non-``$ref`` shape refuses.
        if not schema.get("properties") and schema.get("additionalProperties") is True:
            return "Record<string, unknown>"
        if not schema.get("properties") and isinstance(schema.get("additionalProperties"), dict):
            # dict[str, T] (a typed mapping, not free-form): Record<string, T>.
            return f"Record<string, {_ts_type(schema['additionalProperties'], where)}>"
    if kind == "array":
        if "prefixItems" in schema:
            items = ", ".join(_ts_type(s, where) for s in schema["prefixItems"])
            return f"[{items}]"
        if "items" in schema:
            item_schema = schema["items"]
            item_type = _ts_type(item_schema, where)
            # A top-level union (anyOf, or an enum of more than one member) renders bare, with no
            # brackets of its own; parenthesize it so an array of it reads as ``(A | B)[]``.
            if "anyOf" in item_schema or len(item_schema.get("enum", [])) > 1:
                item_type = f"({item_type})"
            return f"{item_type}[]"
    raise SystemExit(f"generate_frontend_types.py cannot map the schema for {where}: {schema}")


def _interface(name: str, schema: dict) -> str:
    """One ``export interface`` block for a model's own JSON schema."""
    required = set(schema.get("required", []))
    lines = [f"export interface {name} {{\n"]
    for prop, prop_schema in schema.get("properties", {}).items():
        optional = "" if prop in required else "?"
        lines.append(f"  {prop}{optional}: {_ts_type(prop_schema, f'{name}.{prop}')};\n")
    lines.append("}\n")
    return "".join(lines)


def render() -> str:
    """The full text of the generated module."""
    models = declared_models()
    _, combined = models_json_schema([(m, "validation") for m in models])
    defs = combined["$defs"]
    body = "\n".join(_interface(m.__name__, defs[m.__name__]) for m in models)
    constant = f"export const RENDER_CACHE_VERSION = {render_cache_version()};\n\n"
    header_const = f"export const IMAGE_ERROR_HEADER = {json.dumps(image_error_header())};\n\n"
    overviews_const = f"export const OVERVIEWS_REQUIRED = {json.dumps(overviews_required())};\n\n"
    tabs = ", ".join(json.dumps(t) for t in tab_names())
    tab_names_const = f"export const TAB_NAMES = [{tabs}] as const;\n\n"
    panel_event_names = "".join(
        f"export const {name} = {json.dumps(value)};\n"
        for name, value in platform_panel_event_constants())
    panel_events = ", ".join(json.dumps(t) for t in platform_panel_events())
    panel_events_const = (
        panel_event_names
        + f"\nexport const PLATFORM_PANEL_EVENTS = [{panel_events}] as const;\n\n"
    )
    terminal = ", ".join(json.dumps(t) for t in terminal_statuses())
    terminal_const = f"export const TERMINAL_STATUSES = [{terminal}] as const;\n\n"
    job_status = " | ".join(json.dumps(t) for t in job_status_members())
    job_status_alias = f"export type JobStatus = {job_status};\n\n"
    return (HEADER + constant + header_const + overviews_const + tab_names_const
            + panel_events_const + terminal_const + job_status_alias + body)


def main() -> int:
    GENERATED_PATH.write_text(render(), encoding="utf-8", newline="\n")
    print(f"wrote {GENERATED_PATH}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
